# Generated by Django 4.1.3 on 2022-11-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=18)),
                ('last_name', models.CharField(max_length=18)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Student', 'Student'), ('Teaching Assistant', 'Teaching Assistant'), ('Teacher', 'Teacher')], default='Student', max_length=18),
        ),
    ]
