# Generated by Django 4.1.3 on 2022-11-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0003_course_coursework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coursework_name', to='coursework.course'),
        ),
    ]
