# Generated by Django 4.1.3 on 2022-11-28 04:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0004_alter_coursework_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursework',
            name='taken_person',
            field=models.ManyToManyField(blank=True, related_name='coursework_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
