# Generated by Django 4.1.3 on 2022-11-28 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0005_alter_coursework_taken_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('coursework', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='coursework.coursework')),
            ],
        ),
        migrations.CreateModel(
            name='AssigmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_status', to='coursework.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
