# Generated by Django 4.1.3 on 2022-11-28 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0006_assignment_assigmentstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigmentstatus',
            old_name='status',
            new_name='upload_status',
        ),
        migrations.AlterField(
            model_name='assigmentstatus',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='coursework.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='coursework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='coursework.coursework'),
        ),
    ]
