# Generated by Django 4.1.3 on 2022-11-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0008_assigmentstatus_memo_assigmentstatus_upload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursework',
            options={'ordering': ['course']},
        ),
    ]
