# Generated by Django 4.1.3 on 2022-11-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0013_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
