# Generated by Django 4.1.3 on 2022-12-01 07:10

import coursework.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0015_alter_assigmentstatus_upload_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigmentstatus',
            name='upload_file',
        ),
        migrations.RemoveField(
            model_name='assigmentstatus',
            name='upload_status',
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=coursework.models.path_and_rename)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_file', to='coursework.assigmentstatus')),
            ],
        ),
    ]
