# Generated by Django 4.1.3 on 2022-12-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0016_remove_assigmentstatus_upload_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to='upload'),
        ),
    ]
