# Generated by Django 4.1.3 on 2022-12-01 07:15

import coursework.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0017_alter_uploadfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(upload_to=coursework.models.path_and_rename),
        ),
    ]
