# Generated by Django 4.1.3 on 2022-12-02 07:20

import coursework.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0019_alter_assignment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=coursework.models.path_and_rename),
        ),
    ]
