# Generated by Django 4.1.3 on 2022-12-02 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0020_alter_uploadfile_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AssigmentStatus',
            new_name='AssignmentStatus',
        ),
    ]
