# Generated by Django 4.1.3 on 2022-12-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0021_rename_assigmentstatus_assignmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
