# Generated by Django 4.1.3 on 2022-12-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0023_remove_assignment_is_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentstatus',
            name='memo',
            field=models.TextField(null=True),
        ),
    ]
