# Generated by Django 4.1.3 on 2022-12-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0024_alter_assignmentstatus_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentstatus',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
