# Generated by Django 4.1.3 on 2022-12-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0025_alter_assignmentstatus_memo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignmentstatus',
            options={'ordering': ['assignment', 'student__username']},
        ),
        migrations.AlterModelOptions(
            name='studentlist',
            options={'ordering': ['student_id']},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['assignment', 'assignment__student', 'file']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.CreateModel(
            name='ZipFileForDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_zip_file', to='coursework.assignment')),
            ],
        ),
    ]
