# Generated by Django 4.1.3 on 2022-12-05 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0026_alter_assignmentstatus_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZipFileForDownload',
        ),
    ]
