# Generated by Django 4.1.3 on 2022-12-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0028_zipfile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ZipFile',
            new_name='ResultZipFile',
        ),
    ]
