# Generated by Django 4.1.3 on 2022-12-07 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0031_alter_assignment_result_zip_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinCourseworkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("approve", models.BooleanField(default=False)),
                (
                    "request_coursework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coursework.coursework",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_student",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
