# Generated by Django 4.1.3 on 2022-12-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0032_joincourseworkrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="JoinCourseworkRequest",
        ),
    ]
