# Generated by Django 4.1.3 on 2022-12-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0034_joincourseworkrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="joincourseworkrequest",
            options={"ordering": ["student", "coursework"]},
        ),
        migrations.RemoveField(
            model_name="joincourseworkrequest",
            name="approve",
        ),
    ]
